name: Deploy Telegram Bot to Google Cloud VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Connect to Google VM and redeploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCE_INSTANCE_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/pleshakov/nutrition-mngr-tg-bot

            echo "🧹 Cleaning up old containers and volumes..."
            docker-compose down -v || true
            docker volume prune -f || true
            docker network prune -f || true

            echo "📦 Pulling latest code from GitHub..."
            git pull origin master

            echo "🔨 Rebuilding without cache..."
            docker-compose build --no-cache

            echo "🚀 Starting bot..."
            docker-compose up -d
